#!/usr/bin/env python3
"""Build Shopify Liquid collection copy from the editable content source."""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / 'content/collection-seo.json').read_text())
records = source['collections']
assert len({record['handle'] for record in records}) == len(records)

def escape(value):
    assert '{{' not in value and '{%' not in value, 'Copy must not contain Liquid code'
    return html.escape(value, quote=False)

def paragraph(value):
    return '<p>' + escape(value) + '</p>'

lines = [
    '{%- comment -%}',
    'Generated by scripts/build-collection-seo.py from content/collection-seo.json.',
    'Edit the source and rebuild; unmatched collections retain their metafield content.',
    '{%- endcomment -%}',
    "{%- if request.locale.iso_code == 'en' -%}",
    '{%- case collection.handle -%}',
]
for record in records:
    lines += ["{%- when '" + record['handle'] + "' -%}"]
    for part, key in [('title', 'title'), ('description', 'meta_description'), ('h1', 'h1')]:
        assert '<' not in record[key] and '{{' not in record[key] and '{%' not in record[key]
        lines += ['{%- capture seo_' + part + ' -%}', record[key], '{%- endcapture -%}']
    lines += ['{%- capture seo_intro -%}', '<h2>' + escape(record['heading']) + '</h2>', paragraph(record['intro']), '{%- endcapture -%}']
    lines += ['{%- capture seo_full -%}', '<h3>' + escape(record['guide_title']) + '</h3>', paragraph(record['guide']), '<h3>' + escape(record['question']) + '</h3>', paragraph(record['answer'])]
    links = []
    for handle, label in record['links']:
        assert handle in {row['handle'] for row in records}, f'Unknown collection link: {handle}'
        url = "{{ collections['" + handle + "'].url | default: '/collections/" + handle + "' }}"
        links.append('<a href="' + url + '">' + escape(label) + '</a>')
    lines += ['<p>Explore related collections: ' + ' · '.join(links) + '.</p>', '{%- endcapture -%}']
lines += ['{%- endcase -%}', '{%- case part -%}']
for part in ['title', 'description', 'h1', 'intro', 'full']:
    lines += ["{%- when '" + part + "' -%}", '{{- seo_' + part + ' -}}']
lines += ['{%- endcase -%}', '{%- endif -%}']
(ROOT / 'snippets/collection-seo-copy.liquid').write_text('\n'.join(lines) + '\n')
print(f'Built copy for {len(records)} collections.')
