"""Combine adjacent global styles without changing their cascade order."""
from pathlib import Path

assets = Path(__file__).resolve().parents[1] / "assets"
sources = ["brand-system.css", "add-to-cart-animation.css", "storefront-improvements.css"]
output = "/* Generated by scripts/build-storefront-css.py; edit source styles. */\n"
for name in sources:
    output += f"\n/* {name} */\n" + (assets / name).read_text() + "\n"
(assets / "storefront-bundle.css").write_text(output)
