"""Build the runtime Dunamiss stylesheets from their documented sources."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
SOURCES = ROOT / "styles" / "dunamiss"

GLOBAL_SOURCES = (
    "foundations.css",
    "add-to-cart.css",
    "components.css",
    "typography.css",
    "product-ingredients.css",
)


def generated_header() -> str:
    return (
        "/* Generated by scripts/build-storefront-css.py. "
        "Edit styles/dunamiss source files. */\n"
    )


def build_global() -> str:
    output = generated_header()
    for name in GLOBAL_SOURCES:
        output += f"\n/* styles/dunamiss/{name} */\n"
        output += (SOURCES / name).read_text() + "\n"
    return output


ASSETS.joinpath("dunamiss-global.css").write_text(build_global())
ASSETS.joinpath("dunamiss-foundations.css").write_text(
    generated_header() + SOURCES.joinpath("foundations.css").read_text()
)
